[project]
name = "fist"
version = "0.0.1"
description = "a fast, intuitive and sensitive test"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "requests",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "bcrypt==4.0.1",  # Pin bcrypt to 4.0.1 for compatibility with passlib 1.7.4
]
