[project]
name = "fist"
version = "0.0.1"
description = "a fast, intuitive and sensitive test"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "python-multipart",
    "requests",
    "jinja2",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
]
