"""Type stubs for NLTK library."""
from typing import List, Dict, Any, Optional, Tuple

def download(info_or_id: str, quiet: bool = False) -> bool: ...

class corpus:
    class stopwords:
        @staticmethod
        def words(language: str = "english") -> List[str]: ...

class tokenize:
    def word_tokenize(text: str, language: str = "english") -> List[str]: ...
    def sent_tokenize(text: str, language: str = "english") -> List[str]: ...

class stem:
    class WordNetLemmatizer:
        def __init__(self) -> None: ...
        def lemmatize(self, word: str) -> str: ...

def pos_tag(tokens: List[str]) -> List[Tuple[str, str]]: ...
